# Generated by Django 5.0.3 on 2024-03-24 12:32
import uuid

from django.db import migrations

def gen_uuid(apps, schema_editor):
    client = apps.get_model("client", "client")
    for row in client.objects.all():
        row.uuid = uuid.uuid4()
        row.save(update_fields=["uuid"])

class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_remove_serviceprovider_clinetid_newuser_email_and_more'),
    ]

    operations = [
        # omit reverse_code=... if you don't want the migration to be reversible.
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]
