# Generated by Django 5.0.3 on 2024-04-11 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0010_remove_fileupload_id_fileupload_fileid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprovider',
            name='pan',
            field=models.CharField(default=None, max_length=10, unique=True),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='panName',
            field=models.CharField(default=None, max_length=200, unique=True),
        ),
    ]
