# Generated by Django 5.0.3 on 2024-04-23 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0013_booked_customerlist_remove_section_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerlist',
            name='email',
            field=models.EmailField(max_length=254, null=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='customerlist',
            name='username',
            field=models.CharField(max_length=150),
        ),
    ]
