# Generated by Django 5.0.3 on 2024-04-23 18:17

import django.db.models.deletion
from django.db import migrations, models
import uuid

class Migration(migrations.Migration):

    dependencies = [
        ('client', '0015_alter_booked_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='booked',
            name='bookedID',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, null=True),
        ),
        migrations.AddField(
            model_name='customerlist',
            name='customerID',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, null=True),
        ),
        migrations.AlterField(
            model_name='booked',
            name='ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.client'),
        ),
        migrations.AlterField(
            model_name='customerlist',
            name='ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.serviceprovider'),
        ),
    ]
