# Generated by Django 5.0.3 on 2024-04-23 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0018_auto_20240423_2348'),
    ]

    operations = [
        migrations.AddField(
            model_name='booked',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
