# Generated by Django 5.0.3 on 2024-04-23 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0020_customerlist_startdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerlist',
            name='startDate',
            field=models.DateField(),
        ),
    ]
