# Generated by Django 5.0.3 on 2024-03-24 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_newuser_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newuser',
            name='email',
        ),
        migrations.AlterField(
            model_name='newuser',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
