# Generated by Django 5.0.3 on 2024-04-23 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0014_alter_customerlist_email_alter_customerlist_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booked',
            name='email',
            field=models.EmailField(max_length=254, null=True, verbose_name='email address'),
        ),
    ]
