# Generated by Django 5.0.3 on 2024-04-23 18:18

from django.db import migrations
import uuid

def gen_uuid(apps, schema_editor):
    MyModel1 = apps.get_model("client", "customerList")
    for row in MyModel1.objects.all():
        row.uuid = uuid.uuid4()
        row.save(update_fields=["uuid"])
    MyModel2 = apps.get_model("client", "booked")
    for row in MyModel2.objects.all():
        row.uuid = uuid.uuid4()
        row.save(update_fields=["uuid"])    

class Migration(migrations.Migration):

    dependencies = [
        ('client', '0016_booked_bookedid_customerlist_customerid_and_more'),
    ]

    operations = [
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]
