# Generated by Django 5.0.3 on 2024-03-24 12:33

from django.db import migrations, models
import uuid

def gen_uuid(apps, schema_editor):
    client = apps.get_model("client", "client")
    for row in client.objects.all():
        row.clientID = uuid.uuid4()
        row.save(update_fields=["clientID"])
        
def gen_uuid(apps, schema_editor):
    client = apps.get_model("client", "client")
    for row in client.objects.all():
        row.userID = uuid.uuid4()
        row.save(update_fields=["userID"])
                
class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_add_unique_chat_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprovider',
            name='clientID',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='userID',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
