# Generated by Django 5.0.3 on 2024-03-28 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0008_newuser_is_active_newuser_is_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='userType',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
