# Generated by Django 5.0.3 on 2024-04-24 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0013_remove_section_id_remove_servicelist_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerlist',
            name='startDate',
            field=models.DateField(default='2024-04-24'),
        ),
        migrations.AlterField(
            model_name='booked',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
