# Generated by Django 5.0.3 on 2024-04-24 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0014_customerlist_startdate_alter_booked_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerlist',
            name='startDate',
            field=models.DateField(),
        ),
    ]
